# -*- coding: utf-8 -*-
"""XGBoost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IxXuHrBok0vific5B8iB-6YGpx9q0Mzn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import (
    mean_squared_error, r2_score,
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, ConfusionMatrixDisplay
)
from sklearn.model_selection import cross_val_score
from xgboost import XGBRegressor, XGBClassifier

# LOAD DATA
X_train     = pd.read_csv("Project Assignments/models/ml_splits/X_train.csv")
X_test      = pd.read_csv("Project Assignments/models/ml_splits/X_test.csv")
y_reg_train = pd.read_csv("Project Assignments/models/ml_splits/y_reg_train.csv").values.ravel()
y_reg_test  = pd.read_csv("Project Assignments/models/ml_splits/y_reg_test.csv").values.ravel()
y_cls_train = pd.read_csv("Project Assignments/models/ml_splits/y_cls_train.csv").values.ravel()
y_cls_test  = pd.read_csv("Project Assignments/models/ml_splits/y_cls_test.csv").values.ravel()

print("✅ Data loaded successfully")
print(f"   Train rows: {len(X_train)} | Test rows: {len(X_test)}")
print(f"   Features ({X_train.shape[1]}): {list(X_train.columns)}")

# SANITY CHECK
print("\n--- SANITY CHECK ---")
print(f"Regression target — min: {y_reg_train.min()}, max: {y_reg_train.max()}, mean: {y_reg_train.mean():.2f}")
print(f"Classification target — unique values: {np.unique(y_cls_train, return_counts=True)}")

has_both_classes = len(np.unique(y_cls_train)) == 2
if not has_both_classes:
    print("\n⚠️  WARNING: y_cls_train only has one class — CSV files need to be regenerated!")
else:
    print("✅ Both Budget and Premium classes present")

# XGBOOST REGRESSION
print("\n========== XGBOOST REGRESSION ==========")

xgb_reg = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    verbosity=0
)

cv_r2  = cross_val_score(xgb_reg, X_train, y_reg_train, cv=5, scoring="r2")
cv_mse = cross_val_score(xgb_reg, X_train, y_reg_train, cv=5, scoring="neg_mean_squared_error")
print(f"CV R²  scores: {cv_r2.round(4)}  →  avg: {cv_r2.mean():.4f}")
print(f"CV MSE scores: {(-cv_mse).round(2)}  →  avg: {(-cv_mse).mean():.2f}")
print(f"CV RMSE scores: {cv_rmse.round(2)}  →  avg: {cv_rmse.mean():.2f}")

xgb_reg.fit(X_train, y_reg_train)
y_pred_reg = xgb_reg.predict(X_test)

test_mse = mean_squared_error(y_reg_test, y_pred_reg)
test_r2  = r2_score(y_reg_test, y_pred_reg)
print(f"\nTEST SET:")
print(f"  MSE:  {test_mse:.4f}")
print(f"  RMSE: {test_rmse:.4f}  ← avg prediction error in dollars")
print(f"  R²:   {test_r2:.4f}")

# XGBOOST CLASSIFICATION
print("\n========== XGBOOST CLASSIFICATION ==========")

if not has_both_classes:
    print("⚠️  Skipping classification — only one class in training data. Fix your CSVs first.")
else:
    neg = (y_cls_train == 0).sum()
    pos = (y_cls_train == 1).sum()
    spw = neg / pos
    print(f"Class balance — Budget: {neg} | Premium: {pos} | scale_pos_weight: {spw:.2f}")

    xgb_cls = XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=spw,
        random_state=42,
        verbosity=0,
        eval_metric="logloss"
    )

    cv_acc = cross_val_score(xgb_cls, X_train, y_cls_train, cv=5, scoring="accuracy")
    cv_f1  = cross_val_score(xgb_cls, X_train, y_cls_train, cv=5, scoring="f1")
    print(f"CV Accuracy: {cv_acc.round(4)}  →  avg: {cv_acc.mean():.4f}")
    print(f"CV F1:       {cv_f1.round(4)}   →  avg: {cv_f1.mean():.4f}")

    xgb_cls.fit(X_train, y_cls_train)
    y_pred_cls = xgb_cls.predict(X_test)

    print(f"\nTEST SET:")
    print(f"  Accuracy:  {accuracy_score(y_cls_test, y_pred_cls):.4f}")
    print(f"  Precision: {precision_score(y_cls_test, y_pred_cls, zero_division=0):.4f}")
    print(f"  Recall:    {recall_score(y_cls_test, y_pred_cls, zero_division=0):.4f}")
    print(f"  F1-Score:  {f1_score(y_cls_test, y_pred_cls, zero_division=0):.4f}")

# MODEL COMPARISON TABLE
print("\n========== REGRESSION MODEL COMPARISON ==========")
comparison = pd.DataFrame({
    "Model": ["Linear Regression (baseline)", "XGBoost"],
    "MSE":   [70.0, round(test_mse, 4)],
    "RMSE":  [round(np.sqrt(70.00), 2), round(test_rmse, 4)],
    "R²":    [0.14, round(test_r2, 4)],
})
print(comparison.to_string(index=False))

# VISUALIZATIONS

# 1. Actual vs Predicted (Regression)
plt.figure(figsize=(7, 5))
plt.scatter(y_reg_test, y_pred_reg, alpha=0.3, s=10, color="steelblue")
lim = max(y_reg_test.max(), y_pred_reg.max()) if y_reg_test.max() > 0 else 1
plt.plot([0, lim], [0, lim], "r--", lw=1.5, label="Perfect prediction")
plt.xlabel("Actual Price ($)")
plt.ylabel("Predicted Price ($)")
plt.title("XGBoost Regression — Actual vs Predicted")
plt.legend()
plt.tight_layout()
plt.show()

# 2. Residual Plot
residuals = y_reg_test - y_pred_reg
plt.figure(figsize=(7, 5))
plt.scatter(y_pred_reg, residuals, alpha=0.3, s=10, color="darkorange")
plt.axhline(0, color="red", linestyle="--", lw=1.5)
plt.xlabel("Predicted Price ($)")
plt.ylabel("Residuals")
plt.title("XGBoost Regression — Residual Plot")
plt.tight_layout()
plt.show()

# 3. Confusion Matrix (only if classification ran)
if has_both_classes:
    cm = confusion_matrix(y_cls_test, y_pred_cls, labels=[0, 1])
    disp = ConfusionMatrixDisplay(cm, display_labels=["Budget", "Premium"])
    fig, ax = plt.subplots(figsize=(5, 4))
    disp.plot(ax=ax, colorbar=False)
    ax.set_title("XGBoost — Confusion Matrix (Budget vs Premium)")
    plt.tight_layout()
    plt.show()

# 4. Feature Importance — Regression
importances_reg = pd.Series(xgb_reg.feature_importances_, index=X_train.columns)
top15_reg = importances_reg.nlargest(15).sort_values()
plt.figure(figsize=(8, 6))
top15_reg.plot(kind="barh", color="steelblue")
plt.title("XGBoost — Top 15 Feature Importances (Regression)")
plt.xlabel("Importance Score")
plt.tight_layout()
plt.show()

# 5. Feature Importance — Classification
if has_both_classes:
    importances_cls = pd.Series(xgb_cls.feature_importances_, index=X_train.columns)
    top15_cls = importances_cls.nlargest(15).sort_values()
    plt.figure(figsize=(8, 6))
    top15_cls.plot(kind="barh", color="seagreen")
    plt.title("XGBoost — Top 15 Feature Importances (Classification)")
    plt.xlabel("Importance Score")
    plt.tight_layout()
    plt.show()

# SAMPLE PREDICTIONS
print("\n========== SAMPLE PREDICTIONS (first 10 test rows) ==========")
sample = pd.DataFrame({
    "Actual Price ($)":  y_reg_test[:10],
    "XGB Predicted ($)": y_pred_reg[:10].round(2),
    "Error ($)":         (y_reg_test[:10] - y_pred[:10]).round(2),
})
if has_both_classes:
    sample["Actual Label"]   = ["Premium" if v else "Budget" for v in y_cls_test[:10]]
    sample["XGB Label Pred"] = ["Premium" if v else "Budget" for v in y_pred_cls[:10]]
print(sample.to_string(index=False))